name: 'Deploy container image to Cloud Run'
description: 'Deploy container image to Cloud Run'
inputs:
  gcp-project-id:  
    description: 'GCP_PROJECT_ID'
    required: true
  gcp-sa-key:  
    description: 'GCP_SA_KEY'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login GCP 
      run: |
        echo  ${{ inputs.gcp-sa-key }} | base64 --decode > ./gcp-key.json
        gcloud config set disable_prompts false
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ inputs.gcp-project-id }}
        rm gcp-key.json
      shell: bash

    - name: Deploy service.yaml
      run: |
        envsubst < deploys/service.yaml.template > deploys/service.yaml

        cat deploys/service.yaml

        gcloud run services replace deploys/service.yaml
        

      shell: bash

    - name: Logout GCP
      run: |
        gcloud auth revoke --all
        gcloud config unset project
      shell: bash


