name: 'Deploy container image to Cloud Run'
description: 'Deploy container image to Cloud Run'
inputs:
  app-docker-image:
    description: 'image:tag'
    required: true
  promtail-docker-image:
    description: 'image:tag'
    required: true
  gcp-project-id:  
    description: 'GCP_PROJECT_ID'
    required: true
  gcp-sa-key:  
    description: 'GCP_SA_KEY'
    required: true
  service-name:
    description: 'Service name in Cloud Run'
    required: true
  app-name:  
    description: 'App name'
    required: true
  region:
    description: 'Region'
    required: true
  app-port:
    description: 'Port'
    required: true
  memory:
    description: 'Memory (iec)'
    required: true
  cpu:
    description: 'CPU (cores)'
    required: true
  min-instances:
    description: 'Minimum instances for autoscaling'
    required: true
  max-instances:
    description: 'Maximum instances for autoscaling'
    required: true
  timeout:
    description: 'Timeout for deploy (s)'
    required: true
  max-request-bytes:
    description: 'Maximum bytes for request (bytes)'
    required: false
    default: 52428800
  instances-max-scale:
    description: 'Instances max scale'
    required: false
    default: 1
  ingress-status:
    description: 'internal, all'
    required: false
    default: all
  cloudrun-timeout:
    description: 'Cloud Run timeout seconds'
    required: false
    default: '15'
  app-startup-timeout:
    description: 'Timeout for app startup'
    required: false
    default: 240
  vpc-connector-name:
    description: 'Name for existing VCP connector to be used'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login GCP 
      run: |
        echo  ${{ inputs.gcp-sa-key }} | base64 --decode > ./gcp-key.json
        gcloud config set disable_prompts false
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ inputs.gcp-project-id }}
        rm gcp-key.json
      shell: bash

    - name: Deploy service.yaml
      run: |
        echo "GCP_PROJECT_ID=${{ inputs.gcp-project-id }}" >> $GITHUB_ENV
        echo "GCP_REGION=${{ inputs.region }}" >> $GITHUB_ENV

        echo "CR_SERVICE_NAME=${{ inputs.service-name }}" >> $GITHUB_ENV
        echo "CR_MAX_SCALE=${{ inputs.instances-max-scale }}" >> $GITHUB_ENV
        echo "CR_TIMEOUT=${{ inputs.cloudrun-timeout }}" >> $GITHUB_ENV
        echo "CR_APP_MAX_REQUES_BYTES=${{ inputs.max-request-bytes }}" >> $GITHUB_ENV
        echo "CR_APP_STARTUP_TIMEOUT=${{ inputs.app-startup-timeout }}" >> $GITHUB_ENV
        echo "CR_INGRESS_STATUS=${{ inputs.ingress-status }}" >> $GITHUB_ENV
        echo "CR_CONNECTOR_NAME=${{ inputs.vpc-connector-name }}" >> $GITHUB_ENV

        echo "APP_NAME=${{ inputs.app-name }}" >> $GITHUB_ENV
        echo "APP_IMAGE_URL=${{ inputs.app-docker-image }}" >> $GITHUB_ENV
        echo "APP_IMAGE_PORT=${{ inputs.app-port }}" >> $GITHUB_ENV
        echo "APP_CPU_LIMIT=${{ inputs.cpu }}" >> $GITHUB_ENV
        echo "APP_MEMORY_LIMIT=${{ inputs.memory }}" >> $GITHUB_ENV

        echo "PROMTAIL_IMAGE_URL=${{ inputs.promtail-docker-image }}" >> $GITHUB_ENV

        envsubst < deploys/service.yaml.template > deploys/service.yaml

        cat deploys/service.yaml

        gcloud run services replace deploys/service.yaml
        

      shell: bash

    - name: Logout GCP
      run: |
        gcloud auth revoke --all
        gcloud config unset project
      shell: bash


