name: Notify errors
on:
  repository_dispatch:
    types: [ci_failure]
jobs:
  notify:
    environment: ${{ github.event.client_payload.environment }}
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Dispatch payload:" && echo "${{ toJSON(github.event) }}"
      
      - name: Send error logs
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"content": "Error at repository ${{ github.event.client_payload.repository }} on workflow ${{ github.event.client_payload.workflow }}, with run_id ${{ github.event.client_payload.run_id }}"}' \
            "${{ vars.DISCORD_CHANNEL_ERR }}"

